import { NextRequest } from 'next/server'
import { getSession } from '@/lib/kv'
import { renderToBuffer, Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer'
import type { FinalizedOutput } from '@/lib/types'

export const maxDuration = 60

// Register a clean sans-serif font stack (Helvetica is built-in to PDF spec)
const styles = StyleSheet.create({
  page: {
    fontFamily: 'Helvetica',
    fontSize: 10,
    paddingTop: 48,
    paddingBottom: 48,
    paddingHorizontal: 52,
    backgroundColor: '#ffffff',
    color: '#1a1a1a',
  },
  name: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    marginBottom: 2,
    color: '#1a1a1a',
    letterSpacing: 0.5,
  },
  headline: {
    fontSize: 11,
    color: '#4f46e5',
    marginBottom: 12,
    fontFamily: 'Helvetica-Oblique',
  },
  divider: {
    borderBottomWidth: 1.5,
    borderBottomColor: '#4f46e5',
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#6366f1',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 6,
    marginTop: 14,
  },
  about: {
    fontSize: 10,
    color: '#374151',
    lineHeight: 1.55,
  },
  roleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginTop: 8,
    marginBottom: 3,
  },
  roleTitle: {
    fontSize: 10.5,
    fontFamily: 'Helvetica-Bold',
    color: '#111827',
    flex: 1,
  },
  roleCompany: {
    fontSize: 10,
    color: '#6b7280',
    fontFamily: 'Helvetica-Oblique',
  },
  bullet: {
    flexDirection: 'row',
    marginBottom: 3,
    paddingLeft: 4,
  },
  bulletDot: {
    fontSize: 10,
    color: '#4f46e5',
    marginRight: 6,
    marginTop: 1,
  },
  bulletText: {
    fontSize: 10,
    color: '#374151',
    lineHeight: 1.45,
    flex: 1,
  },
  roleDivider: {
    borderBottomWidth: 0.5,
    borderBottomColor: '#e5e7eb',
    marginTop: 8,
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 52,
    right: 52,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: 8,
    color: '#9ca3af',
  },
})

function ResumePDF({ output }: { output: FinalizedOutput }) {
  // Extract name from headline if possible (first part before |)
  const namePart = output.headline.split('|')[0].trim()
  const isName = namePart.split(' ').length <= 4 && !namePart.includes('@')
  const displayName = isName ? namePart : 'Professional Resume'
  const displayHeadline = isName ? output.headline.replace(namePart + ' | ', '') : output.headline

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        {/* Header */}
        <Text style={styles.name}>{displayName}</Text>
        <Text style={styles.headline}>{displayHeadline}</Text>
        <View style={styles.divider} />

        {/* About */}
        {output.about ? (
          <>
            <Text style={styles.sectionTitle}>Professional Summary</Text>
            <Text style={styles.about}>{output.about.replace(/\*\*/g, '').replace(/\*/g, '')}</Text>
          </>
        ) : null}

        {/* Experience */}
        {output.roles && output.roles.length > 0 ? (
          <>
            <Text style={styles.sectionTitle}>Experience</Text>
            {output.roles.map((role, i) => (
              <View key={i}>
                <View style={styles.roleHeader}>
                  <View>
                    <Text style={styles.roleTitle}>{role.title}</Text>
                    <Text style={styles.roleCompany}>{role.company}</Text>
                  </View>
                </View>
                {role.bullets.map((bullet, j) => (
                  <View key={j} style={styles.bullet}>
                    <Text style={styles.bulletDot}>•</Text>
                    <Text style={styles.bulletText}>{bullet.replace(/^\•\s*/, '').replace(/\*\*/g, '')}</Text>
                  </View>
                ))}
                {i < output.roles.length - 1 && <View style={styles.roleDivider} />}
              </View>
            ))}
          </>
        ) : null}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Generated by myprofilecoach.com</Text>
          <Text style={styles.footerText} render={({ pageNumber, totalPages }) =>
            `${pageNumber} / ${totalPages}`
          } />
        </View>
      </Page>
    </Document>
  )
}

export async function POST(request: NextRequest) {
  try {
    const { sessionId } = await request.json() as { sessionId: string }

    if (!sessionId) {
      return new Response('sessionId required', { status: 400 })
    }

    const session = await getSession(sessionId)
    if (!session?.finalizedLinkedIn) {
      return new Response('Session or finalized output not found', { status: 404 })
    }

    const output = session.finalizedLinkedIn

    const buffer = await renderToBuffer(<ResumePDF output={output} />)

    const namePart = output.headline.split('|')[0].trim().replace(/\s+/g, '-').toLowerCase()
    const filename = `resume-${namePart}-optimized.pdf`

    return new Response(buffer as unknown as BodyInit, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${filename}"`,
        'Content-Length': buffer.length.toString(),
      },
    })
  } catch (err) {
    console.error('PDF generation failed:', err)
    return new Response('PDF generation failed', { status: 500 })
  }
}
